# docker-compose.ymlフォーマットのバージョン指定
version: '3'
services:
  # Railsコンテナ定義
  web:
    # Dockerfileを使用してイメージをビルド
    build: .
    # コンテナ起動時のデフォルトコマンド
    # ポート番号：3000
    # バインドするIPアドレス：0.0.0.0
    # ポート3000が来たらrailsサーバーが応答
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # ローカルのsrcをコンテナにマウント
    volumes:
      - ./tutorial:/app
    # コンテナの外部に3000番を公開
    # 公開するポート番号：コンテナ内部の転送先ポート番号
    ports:
      - 3000:3000
    # dbコンテナが先に起動するよう設定
    depends_on:
      - db
    # pryを使用してデバッグができるよう設定
    tty: true
    stdin_open: true
  # MySQLコンテナ定義
  db:
    # mysqlを使用してコンテナ作成
    image: mysql:5.7
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      # ローカルで保持しているDBをコンテナにマウント
      - ./mysql/data:/var/lib/mysql
    # コンテナ内の環境変数を定義
    environment:
      MYSQL_DATABASE: development_db
      MYSQL_USER: development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password

# DBの内容をローカルに保持
volumes:
  db-volume:
